# Use an official Python runtime as a parent image
FROM python:latest

# Set the working directory in the container
WORKDIR /usr/src/app

# Install any needed packages specified in requirements.txt
RUN apt-get update && \
    apt-get install -y pkg-config libmariadb-dev-compat libmariadb-dev gcc default-libmysqlclient-dev && \
    rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /usr/src/app
COPY ./app ./

# Make port 8000 available to the world outside this container
EXPOSE 8103

# Run app.py when the container launches
CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8103", "--reload"]
